import { Project, Experience, SkillCategory, Stat } from "./types";

export const PORTFOLIO_DATA = {
  personalInfo: {
    name: "Divya Prakash Mishra",
    shortName: "Divya",
    title: "Full Stack Developer & Software Architect",
    greeting: "Hi there, I am",
    bio: "Building high-performance web applications with a focus on clean code, scalability, and exceptional user experience. Let's turn your ideas into digital reality.",
    location: "Lucknow, India",
    email: "d1vyaamishra08@gmail.com",
    resumeUrl: "#",
    traits: ["Passionate", "Creative", "Problem Solver", "Detail Oriented"],
  },
  socialLinks: [
    {
      name: "GitHub",
      url: "https://github.com/d1vyamishra/",
      icon: "github",
    },
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/d1vya-prakash-mishra",
      icon: "linkedin",
    },
    {
      name: "Twitter",
      url: "https://x.com/d1vyamishra",
      icon: "twitter",
    },
    {
      name: "Instagram",
      url: "https://instagram.com/v1shal.irl",
      icon: "instagram",
    },
    {
      name: "Reddit",
      url: "https://www.reddit.com/user/d1vya_mishra/",
      icon: "reddit",
    },
  ],
  stats: [
    { val: 15, label: "Projects completed" },
    { val: 500, label: "Commits last year" },
    { val: 20, label: "Happy Clients" },
  ] as Stat[],
  skillCategories: [
    {
      title: "Frontend",
      icon: "Layout",
      skills: [
        { name: "React", level: 95 },
        { name: "Vue.js", level: 85 },
        { name: "TypeScript", level: 90 },
        { name: "Next.js", level: 88 },
      ],
    },
    {
      title: "Backend",
      icon: "Server",
      skills: [
        { name: "Node.js", level: 92 },
        { name: "Express", level: 90 },
        { name: "MongoDB", level: 85 },
        { name: "PostgreSQL", level: 80 },
      ],
    },
    {
      title: "Tools & Others",
      icon: "Wrench",
      skills: [
        { name: "Git", level: 95 },
        { name: "Docker", level: 75 },
        { name: "AWS", level: 70 },
        { name: "Figma", level: 88 },
      ],
    },
  ] as SkillCategory[],
  experiences: [
    {
      id: "exp1",
      yearRange: "2023 - Present",
      title: "Senior Full Stack Developer",
      company: "Tech Innovators Inc.",
      description: "Leading the development of enterprise-grade web applications using Next.js, Microservices, and Cloud Native principles.",
      achievements: [
        "Mentored a team of 5 multi-functional developers on best React and Node.js practices.",
        "Streamlined continuous integration, improving production deployment rates by 40%.",
        "Optimized microservice API logic reducing server response times by 30%.",
      ],
      tags: ["Next.js", "Node.js", "Docker", "AWS", "TypeScript", "Prisma"],
      isCurrent: true,
    },
    {
      id: "exp2",
      yearRange: "2021 - 2023",
      title: "Web Developer",
      company: "Creative Solutions Agency",
      description: "Developed and shipped high-traffic e-commerce platforms, customer database systems, and telemetry dashboards.",
      achievements: [
        "Re-engineered legacy web systems resulting in a 25% increase in conversion metrics.",
        "Collaborated closely with visual designers to implement pixel-perfect user journeys.",
      ],
      tags: ["React", "Express", "MongoDB", "Redux", "Tailwind CSS", "REST API"],
    },
    {
      id: "exp3",
      yearRange: "2019 - 2021",
      title: "Junior Developer",
      company: "Startup Hub",
      description: "Focused on developing core product UI interfaces, dynamic API integrations, and executing agile code feedback loops.",
      achievements: [
        "Shipped over 30 custom interactive widgets across client platforms.",
        "Mastered developer workflow environments including modern Git and CI practices.",
      ],
      tags: ["HTML", "CSS", "JavaScript", "jQuery", "Git", "Bootstrap"],
    },
  ] as Experience[],
  projects: [
    {
      id: "p1",
      title: "Nebula E-Commerce",
      description: "A secure, fully functional online platform featuring real-time inventory tracking and custom Stripe checkout flows.",
      tags: ["Next.js", "Stripe API", "Prisma", "PostgreSQL", "Tailwind CSS"],
      category: "fullstack",
      githubUrl: "https://github.com/d1vyamishra/nebula-ecommerce",
      liveUrl: "https://github.com/d1vyamishra/nebula-ecommerce",
      icon: "ShoppingBag",
    },
    {
      id: "p2",
      title: "SaaS Analytics Pro",
      description: "An advanced business telemetry and data analytics visualizer leveraging interactive D3 graph rendering engines.",
      tags: ["React", "D3.js", "Firebase Auth", "TypeScript", "Tailwind CSS"],
      category: "frontend",
      githubUrl: "https://github.com/d1vyamishra/saas-analytics",
      liveUrl: "https://github.com/d1vyamishra/saas-analytics",
      icon: "ChartPie",
    },
    {
      id: "p3",
      title: "Real-Time Team Collab",
      description: "A fast, concurrent communication ecosystem featuring real-time multi-channel messaging and active document sharing.",
      tags: ["React", "Socket.io", "Express", "Redis", "CSS Grid"],
      category: "backend",
      githubUrl: "https://github.com/d1vyamishra/realtime-collab",
      liveUrl: "https://github.com/d1vyamishra/realtime-collab",
      icon: "MessageSquare",
    },
    {
      id: "p4",
      title: "Quantum Task Board",
      description: "An interactive project planner with fluid drag-and-drop mechanics, automated task aging, and team activity analytics.",
      tags: ["TypeScript", "Next.js", "React Joyride", "Framer Motion"],
      category: "frontend",
      githubUrl: "https://github.com/d1vyamishra/quantum-board",
      liveUrl: "https://github.com/d1vyamishra/quantum-board",
      icon: "CheckSquare",
    },
    {
      id: "p5",
      title: "Helios API Mesh",
      description: "A high-performance gateway proxies layer compiling heterogeneous microservice APIs cleanly into a central broker.",
      tags: ["Node.js", "Express", "GraphQL", "Redis Caching", "Docker"],
      category: "backend",
      githubUrl: "https://github.com/d1vyamishra/helios-mesh",
      liveUrl: "https://github.com/d1vyamishra/helios-mesh",
      icon: "Share2",
    },
  ] as Project[],
};
